### ISSUE TITLE
Shooting arrows causes game crash in 1.16.5 version

### ISSUE THREAD

**Issue by hashalite** [MinecraftFreecam/Freecam#169]
From Curseforge comments:

There's a bug in 1.16.5

Trying to shoot an arrow will crash the game.

**Comment by hashalite** [comment]
Possibly related:

error on 1.16.5.

eating while freecamming will crash the game

**Comment by hashalite** [comment]
Although Freecam 1.16 is currently unsupported post the multiversion build script change, I was able to reproduce on the latest available 1.16.5 version - 1.3.5+mc1.16.5

With default Freecam config:
1. Enter Freecam (F4)
2. Attempt to use a bow or food item
3. Below error occurs:


```
[21:15:46] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:568) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1556) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:517) [fabric-loader-0.19.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) [fabric-loader-0.19.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.19.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:115) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.class_1309.method_5998(class_1309.java:1818) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:2814) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2210) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:205) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:193) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[client-intermediary.jar:?]
	... 11 more
```
