### ISSUE TITLE
error occurs when open mod menu

### ISSUE THREAD

**Issue by hATrayflood** [MinecraftFreecam/Freecam#178]
![image](https://github.com/MinecraftFreecam/Freecam/assets/2013010/2c292dd0-e182-445b-bb53-ea12cad24a47)

minecraft version: fabric-loader-0.15.6-1.20.4

mods
```
advanced-xray-fabric-84.0.0.jar
c2me-fabric-mc1.20.4-0.2.0+alpha.11.40.jar
CocoaInput-1.20.2-fabric-4.0.10-PREVIEW2.jar
continuity-3.0.0-beta.4+1.20.2.jar
dynamic-fps-3.3.3+minecraft-1.20.0.jar
enhancedblockentities-0.9.1+1.20.2.jar
entityculling-fabric-1.6.3.1-mc1.20.4.jar
fabric-api-0.95.1+1.20.4.jar
ferritecore-6.0.3-fabric.jar
freecam-fabric-modrinth-1.2.1.1+1.20.jar
ImmediatelyFast-Fabric-1.2.8+1.20.4.jar
indium-1.0.28+mc1.20.4.jar
iris-mc1.20.4-1.6.14.jar
Jade-1.20.4-fabric-13.3.1.jar
krypton-0.2.6.jar
lazydfu-0.1.3.jar
litematica-fabric-1.20.4-0.17.0.jar
lithium-fabric-mc1.20.4-0.12.1.jar
malilib-fabric-1.20.4-0.18.0.jar
memoryleakfix-forge-1.17+-1.1.5.jar
minihud-fabric-1.20.4-0.30.0.jar
modmenu-9.0.0.jar
moreculling-1.20.4-0.22.1.jar
reeses_sodium_options-1.7.0+mc1.20.2-build.97.jar
sodium-extra-0.5.3+mc1.20.2-build.114.jar
sodium-fabric-mc1.20.3-0.5.5.jar
starlight-1.1.3+fabric.f5dcd1a.jar
your-reputation-0.2.5+jade.1.20.jar
```

stack trace
```
Error from mod 'cloth-config'
java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.AbstractTextFieldListListEntry$AbstractTextFieldListCell$1 overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at me.shedaniel.clothconfig2.gui.entries.DoubleListListEntry.<init>(DoubleListListEntry.java:54)
	at me.shedaniel.clothconfig2.impl.builders.DoubleListBuilder.build(DoubleListBuilder.java:151)
	at me.shedaniel.clothconfig2.ClothConfigDemo.getConfigBuilderWithDemo(ClothConfigDemo.java:94)
	at me.shedaniel.clothconfig2.fabric.ClothConfigModMenuDemo.lambda$getModConfigScreenFactory$0(ClothConfigModMenuDemo.java:35)
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:62)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:106)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Error from mod 'freecam'
java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.TextFieldListEntry$1 overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at me.shedaniel.clothconfig2.impl.builders.DoubleFieldBuilder.build(DoubleFieldBuilder.java:109)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$apply$78(DefaultGuiProviders.java:414)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74)
	at java.base/java.util.Optional.map(Optional.java:260)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51)
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$getChildren$96(DefaultGuiProviders.java:538)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:543)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:530)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$apply$15(DefaultGuiProviders.java:141)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74)
	at java.base/java.util.Optional.map(Optional.java:260)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51)
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$5(ConfigScreenProvider.java:129)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$6(ConfigScreenProvider.java:126)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.get(ConfigScreenProvider.java:125)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.get(ConfigScreenProvider.java:45)
	at net.xolt.freecam.config.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:14)
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:62)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:106)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

to avoid error:
add cloth-config-13.0.121-fabric.jar to mods folder.

**Comment by MattSturgeon** [comment]
Do you still get this error on the latest version of Freecam (1.2.3)?

**Comment by hATrayflood** [comment]
thanks. I missed 1.2.3.
